material_kind = {
    "eng": {
        "Painting": [
            "denim",
            "masonite",
            "wooden board",
            "linen",
            "canvas",
            "hemp cloth",
            "fabric",
            "vellum",
            "plywood",
            "wood",
            "hemp",
            "cotton",
            "panel",
            "vinyl",
            "wooden panel",
            "mdf",
            "jute",
            "hardboard",
            "wood board",
            "board",
            "silk",
            "cloth",
            "burlap",
            "taffeta",
        ],
        "Edition" : [
            # 국내는 Edition, 해외는 Works on Paper
            "print",
            "woodcut",
            "intaligo",
            "etching",
            "drypoint",
            "ingraving",
            "aquatint",
            "mezzotint",
            "screenprint",
            "silkscreen",
            "serigraph",
            "stencil",
            "lithograph",
            "linolum cut",
            "linocut",
            "rubber print",
            "offset lithograph",
            "offset print",
            "digital inkjet print",
            "inkjet print",
            "digital print",
            "digital pigment print",
            "achaival pigment print",
            "giclée print",
            "giclee print",
            "monoprint",
            "monotype",
            "archival inkjet",
            "collagraph",
        ],
        "Works on Paper": [
            "envelope",
            "korean paper",
            "card",
            "mixograph",
            "paper",
            "newspaper",
            "postcard",
            "hardboard paper",
            "dak paper",
            "photomontage",
            "dibond",
            "hanji paper",
            "manuscript paper",
            "hanji",
            "dak",
            "ingraving",
            "chinese paper",
            "pigment ink",
            "japanese paper",
            "photogravure",
            "drypoint",
            "cardboard",
        ],
        "Multi-media": [
            "digital work",
            "monitor",
            "video",
            "screen",
            "speaker",
            "audio",
            "installation",
            "computer",
            "dvd",
            "lcd",
            "led",
        ],
        "Sculpture": [
            "copper",
            "glass",
            "metal",
            "neon",
            "blanket",
            "marble",
            "earthenware",
            "ceramic",
            "glazed ceramic",
            "stone",
            "rug",
            "resin",
            "wool",
            "bronze",
            "vinyl resin",
            "stoneware",
            "stainless steel",
            "steel",
            "aluminium",
            "aluminum",
            "oak",
            "iron",
            "tapestry",
            "tile",
            "terracotta",
            "clay",
            "polylaminate",
            "porcelain",
            "polyester",
            "polyurethane",
            "plaster",
            "plastic",
            "plexiglas",
            "alloy",
            "synthetic fiber",
            "synthetic resin",
            "mixed media",
            "granite",
            "ebony",
            "ebondy",
            "frp",
            "pvc",
            "cast vinyl",
            "leather",
            "brass",
            "walnut",
            "velvet",
        ],
        "Photo": [
            "c-print",
            "lambda print",
            "lenticular",
            "platinum print",
            "photograph",
            "cibachrome print",
            "chromogenic color print",
            "ultrachrome inkjet print",
            "gelatin silver print",
            "chromogenic print",
            "palladium print",
            "polaroid",
            "argentique",
            "mylar",
        ],
        "NFT": ["contract adress", "minted", "nft", "token id", "non-fungible token"],
    },
    "kor": {
        "Painting": [
            "코튼",
            "린넨",
            "비단",
            "합판",
            "목판",
            "판넬",
            "마대",
            "나무",
            "실크",
            "천",
            "삼베",
            "하드보드",
            "마포",
            "나무패널",
            "메소나이트",
            "캔버스",
            "독피지",
            "나무보드",
            "견",
            "직물",
            "황마",
            "  보드",
            "면포",
            "면",
            "컨버스",
            "패브릭",
            "데님",
            "비닐",
            "아마",
            "섬유판",
            "패널",
            "마",
            "리넨",
            "견본채색",
            "견본수묵",
        ],
        "Edition" : [
            # 국내는 Edition, 해외는 Works on Paper
            "  프린트",
            "목판화",
            "동판화",
            "석판화",
            "우드컷",
            "인텔리고",
            "애칭",
            "에칭",
            "드라이포인트",
            "인그레이빙",
            "아쿼틴트",
            "애쿼틴트",
            "메조틴트",
            "스크린프린트",
            "실크스크린",
            "세리그라프",
            "세리그래프",
            "리노컷",
            "리놀륨",
            "리놀륨컷",
            "고무판화",
            "오프셋석판화",
            "오프셋프린트",
            "잉크젯프린트",
            "디지털잉크젯프린트",
            "디지털프린트",
            "디지털피그먼트프린트",
            "아카이벌잉크젯프린트",
            "아카이벌피그먼트프린트",
            "지클레이프린트",
            "모노프린트",
            "콜라그래프",
            "판화",


        ],
        "Works on Paper": [
            "골판지",
            "다이본드",
            "닥종이",
            "닥판",
            "닥지",
            "닥",
            "두방지",
            "모노타입",
            "봉투",
            "순지",
            "스텐실",
            "신문지",
            "엽서",
            "오목판화",
            "원고지",
            "장지",
            "종이",
            "종이봉투",
            "지본채색",
            "지본수묵",
            "카드",
            "카드보드",
            "편지봉투",
            "포스트카드",
            "포토몽타주",
            "포토그라비어",
            "포토그라비아",
            "피그먼트프린트",
            "하드보드지",
            "한지",
            "화선지",
            "믹소그래프",
            "믹소그라피아",
            "피그먼트잉크",
        ],
        "Multi-media": [
            "디지털작품",
            "모니터",
            "비디오",
            "스크린",
            "스피커",
            "오디오",
            "인스툴레이션",
            "컴퓨터",
            "디비디",
            "액정디스플레이",
            "발광다이오드",
        ],
        "Sculpture": [
            "구리",
            "글래스",
            "금속",
            "네온",
            "담요",
            "대리석",
            "도기",
            "도자",
            "도자기",
            "돌",
            "러그",
            "레진",
            "모",
            "백자토",
            "브론즈",
            "비닐레진",
            "석기",
            "세라믹",
            "스테인리스",
            "스테인레스",
            "스틸",
            "알루미늄",
            "오크",
            "유리",
            "자기",
            "철",
            "태피스트리",
            "타피스트리",
            "타일",
            "테라코타",
            "토기",
            "폴리라미네이트",
            "포슬린",
            "폴리에스터",
            "폴리에스테르",
            "폴리우레탄",
            "플라스터",
            "플라스틱",
            "플렉시글라스",
            "합금",
            "합성섬유",
            "합성수지",
            "혼합재료",
            "화강암",
            "흑단",
            "섬유강화플라스틱",
            "폴리염화비닐",
            "캐스트 바이닐",
            "레더",
            "가죽",
            "황동",
            "월넛",
            "벨벳",
            "우단",
        ],
        "Photo": [
            "c-프린트" "람다프린트",
            "렌티큘러",
            "백금프린트",
            "사진",
            "시바크롬프린트",
            "울트라크롬잉크젯프린트",
            "젤라틴실버프린트",
            "크로모제닉프린트",
            "팔라듐프린트",
            "폴라로이드",
            "필름",
            "크로모제닉컬러프린트",
        ],
        "Books&Manuscripts":[
            "필사본",
            "묵서"
        ]
    },
}
